site_name: Raz Besaleli
site_url: https://besaleli.github.io/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  font:
    text: B612
  icon:
    logo: material/circle-outline
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

repo_url: https://github.com/besaleli
repo_name: besaleli

nav:
  - About Me: index.md
  - CV: cv.md
  - Blog:
    - blog/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - blog
